### ISSUE TITLE
Warnings in Dioxus 0.6

### ISSUE THREAD

**Issue by JustSimplyKyle** [dioxus-community/dioxus-radio#17]
- Pressing the "add new list" button will incur a `write on signal when a component was running` error.
- Pressing "add new list", "new item", finally "add new list" will incur a `copy_value_hoisted` error.
# Repro
the example is modified with inclusion of dioxus_logger so we can see the warnings.

**Comment by marc2332** [comment]
hey, I am trying with the latest rc.0 and I don't see this issues

**Comment by marc2332** [comment]
Can you try with https://github.com/dioxus-community/dioxus-radio/commit/7f90142234fdc7976c106a8b5c47788851b2e74a ?

**Comment by marc2332** [comment]
I'd appreciate if you could share a repro

**Comment by JustSimplyKyle** [comment]
Modify the `demo.rs` to be as following.

**Comment by marc2332** [comment]
Okay, well, these should be definitely addressed, but I wouldn't call them "issues", they might in fact be false positives, will have a look though

**Comment by marc2332** [comment]
Fixed and released with 0.6 support! https://crates.io/crates/dioxus-radio
